---
title: "SAGES - Predicting GCP slope"
author: "Doug Tommet"
date: '`r Sys.Date()`'
format:
  html:
    toc: true
    self-contained: true
    theme: journal
figures:
  fig-cap-location: top 
execute:
  echo: false
  warning: false
  message: false
keep-md: true
---


```{r}
source(here::here("r", "001-libraries.r"))
source(here::here("r", "002-folder_paths_and_options.r"))

```

```{r}
#| eval: false

source(here::here("r", "010-read_data.r"))
source(here::here("r", "015-transform_labs.r"))
source(here::here("r", "020-transform_data.r"))
source(here::here("r", "021-create_variable_metadata.r"))
source(here::here("r", "022-select_variables.r"))

source(here::here("r", "060-implement_rms.r"))
source(here::here("r", "062-finish_rms.r"))
source(here::here("r", "065-specify_models.r"))
source(here::here("r", "070-fit_models.r"))

source(here::here("r", "082-finish_rms_del.r"))
source(here::here("r", "085-specify_models_del.r"))
source(here::here("r", "090-fit_models_del.r"))

```

{{< include _001-vsr-intro.qmd >}}

<!-- {{< include _010-vsr-read_data.qmd >}} -->

<!-- {{< include _015-vsr-transform_labs.qmd >}} -->

<!-- {{< include _020-vsr-transform_data.qmd >}} -->

<!-- {{< include _021-vsr-create_variable_metadata.qmd >}} -->

<!-- {{< include _060-vsr-implement_rms.qmd >}} -->

<!-- {{< include _062-vsr-finish_rms.qmd >}} -->

<!-- {{< include _001-intro.qmd >}} -->

<!-- {{< include _010-read_data.qmd >}} -->

<!-- {{< include _015-transform_labs.qmd >}} -->

<!-- {{< include _020-transform_data.qmd >}} -->

<!-- {{< include _021-create_variable_metadata.qmd >}} -->

<!-- {{< include _060-implement_rms.qmd >}} -->

<!-- {{< include _065-specify_models.qmd >}} -->

{{< include _070-fit_models.qmd >}}

<!-- {{< include _082-vsr-finish_rms_del.qmd >}} -->

<!-- {{< include _085-specify_models_del.qmd >}} -->

{{< include _090-fit_models_del.qmd >}}



